// Code generated by dtogen. DO NOT EDIT.
package testdata

import ()

type UserDTO struct {
	ID        int    `json:"id"`
	Username  string `json:"username"`
	IsActive  bool
	CreatedAt string
}

func ToUserDTO(in *User) *UserDTO {
	if in == nil {
		return nil
	}

	out := UserDTO{
		ID:        in.ID,
		Username:  in.Username,
		IsActive:  in.IsActive,
		CreatedAt: in.CreatedAt,
	}

	if IsActive {
		out.Username = "Active"
		out.ID = 0

	}

	if IsActive {
		out.Username = "Rdo Active"
		out.ID = 1000

	}

	return &out
}

func ToUserDTOList(list []User) []UserDTO {
	if list == nil {
		return nil
	}
	dtos := make([]UserDTO, len(list))
	for i, v := range list {
		dtos[i] = *ToUserDTO(&v)
	}
	return dtos
}

func (d UserDTO) IsDTO() {}
