// Code generated by dtogen. DO NOT EDIT.
package testdata

type UserDTO struct {
	ID        int    `json:"id"`
	Username  string `json:"username"`
	Email     string
	IsActive  bool
	CreatedAt string
}

func ToUserDTO(v *User) *UserDTO {
	if v == nil {
		return nil
	}
	return &UserDTO{
		ID:        v.ID,
		Username:  v.Username,
		Email:     v.Email,
		IsActive:  v.IsActive,
		CreatedAt: v.CreatedAt,
	}
}
